### PR TITLE
Mantano additions and fixes

### PR DESCRIPTION
**Pull request by mmenu-mantano**
Mantano additions and fixes:

Android:
 - libEPUB3 compatibility with Android pre-lollipop
 - Add Gradle build files
 - Remove talkative logs
 - Expose native Java API to efficiently retrieve manifest items by ID and relative path
 - Expose native Java API to retrieve manifest item's properties (CoverImage, ContainsSVG, etc.)
 - Add native Java API to check if an EPUB 3 property exists in a package
 - Add crash guards in Package

Core SDK:
 - Avoid network requests when loading DTD while parsing XML
 - Add efficient retrieval of manifest items by relative path through hash map
 - Store EPUB 2 properties for backward compatibility from host apps
 - Expose cover manifest item (EPUB 2 and 3 compatible)

### CODE REVIEW

**Comment by danielweck** [comment]
Thank you very much for sharing your code customizations / improvements!
As this is a "bulk" code change, we will need to break down the PR into several well-scoped / atomic updates. I suggest that we identify and extract fragments into `feature/mantano-additions-XXX` branches, individually test + merge them to develop, then re-synchronize the original `feature/mantano-additions` branch with develop, and iterate again. This way, this PR's code diff will gradually shrink down to a more manageable functional scope.
Let's talk about this at the next ReadiumSDK concall?

**Comment by danielweck** [comment]
@TienHai posted a step-by-step guide to create the Android Studio Gradle configuration, I wonder how it compares with this PR's proposed setup:
https://github.com/readium/readium-sdk/issues/180#issuecomment-139166807

**Comment by mmenu-mantano** [comment]
Hello Daniel,

Separating the feature branches is a good idea. I'll do this when I'm less
busy. Unfortunately I won't be able to be there at the meeting, but I
believe the comments on the pull requests should be enough to discuss any
issue.


Thanks,


Mickaël Menu
R&D Engineer


2 rue du Helder - 75009 Paris, France
Tel.: +33 1 42 47 05 61

mmenu@mantano.com
www.mantano.com
store.mantano.com
cloud.mantano.com

**Comment by mmenu-mantano** [comment]
I'm closing this PR and will split the changes progressively to make well-scoped PRs.

**Comment by danielweck** [comment]
Thank you @mmenu-mantano , much appreciated!

**Pull request closed without merging**
