### PR TITLE
Make the SDK compatible with Adobe's DRM Connector Content Filter

### PR DESCRIPTION
**Pull request by mmenu-mantano**
This pull request encompasses a few changes to make Readium compatible with a modified version of Adobe's DRM Connector Content Filter. Thus allowing to decrypt ACS EPUB with Readium without modifying Readium's sources.

If merged in, these changes will allow Adobe to release the RMSDK without including a custom (out-of-date) version of Readium, and be always compatible with the latest version of Readium.

### CODE REVIEW

**Comment by danielweck** [comment]
Is that just a timely coincidence?
https://github.com/readium/readium-sdk/pull/194
Can the above PR (Android-specific) also be used with the proposed `readium-sdk` changes?

**Comment by io7m** [comment]
Hehe, no coincidence. I'm working on the Android side whilst @mmenu-mantano is working on the iOS side!

**Comment by mmenu-mantano** [comment]
Yes as such the PRs are fully compatible. :)

**Comment by danielweck** [comment]
Awesome :)

**Comment by jce1028** [comment]
Adobe re-complied their Adobe Adept connector with NDK 10.  In is in their Beta 11.3 and commercial RMSDK ver 12.

**Comment by danielweck** [comment]
Thanks @jce1028 
If you don't mind I'll quote you there:
https://github.com/readium/readium-sdk/issues/186

**Comment by mmenu-mantano** [comment]
Hello,

What's the status of the DRM-related PRs (this one and #194)? Is anything blocking the merge?

**Comment by danielweck** [comment]
Hello @mmenu-mantano many thanks for your heads-up!
It looks like the `ReadAllBytes` function is introduced specifically to fix `shared_ptr<xml::Document> ManifestItem::ReferencedDocument() const`, which is indeed an important fix to an issue that we have not filed yet! (e.g. encrypted EPUB3 Navigation Document). Let's file this issue, and address it with a well-scoped Pull Request (i.e. that does not contain `containerRegisterFilters`, or mime-type / content-type changes)
Does that make sense?

**Comment by danielweck** [comment]
Okay, I filed the issue:
https://github.com/readium/readium-sdk/issues/200

**Comment by mmenu-mantano** [comment]
Daniel,

Yes I can see that the ReferencedDocument() fix could be its own PR, and it is not specifically related to DRM anyway.
But what about the other more minor and various changes? Do you prefer really small pull requests?

By the way, about the force MIMEtypes part, I don't think it is entirely necessary. Adobe put this in their patch so I let it in case they had some test books that required it. Anyway before the PR Readium was already forcing the MIMEtype for XML and (X)HTML files, so I figured it was not really an issue to expand the list to CSS, SVG and such.

**Comment by mmenu-mantano** [comment]
I created a new PR for the referenced document. Waiting to see what you want to do with the remaining changes before drowning this PR in the limbo.

**Comment by danielweck** [comment]
@mmenu-mantano I don't really understand what `containerRegisterFilters` is for, so I cannot comment on that. Perhaps @nleme and others can chime in to check that this is compatible with their "content filter chain" implementations / customizations (if any).

As for the HTTP `Content-Type` header override, if I remember correctly the intent was to ensure that both HTML and XHTML files were treated as `application/xhtml+xml` by the web-view control (as EPUB3 requires XHTML5 processing), and that XML files were "reduced" to pure `application/xml` instead of mime type extensions such as those used for EPUB3 Bindings (this seemed to help with XMLHTTPRequests in the WebView, IIRC). I am not sure why the other types are necessary, as the OPF package and manifest declarations take care of specifying the correct type (regardless of file extensions).

One design change that we did not mention explicitly on the concall is the move of `BuildFilterChainForPackage()` from `Container::Open()` to `Package::Open()` (just before `unpack()`). This makes a lot of sense, and I think goes hand-in-hand with the introduction of `ReadAllBytes` + `ManifestItem::ReferencedDocument()` => standalone PR.

**Comment by mmenu-mantano** [comment]
The addition of containerRegisterFilters has actually no impact whatsoever on existing behavior. It is just an entry-point for host apps (iOS or Android with #194) to plug custom C++ content filters on-the-fly, without modifying the sources of readium-sdk (PopulateFilterManager() in initialization.cpp). It's a step in the direction of having a more extensible SDK.

I think we can safely ditch the MIMEtype changes and see if this still work with ACS6 files. But it should, if the OPF is properly filled as you said.

**Comment by danielweck** [comment]
Thanks @mmenu-mantano ! :)

**Comment by mmenu-mantano** [comment]
Here is the PR for containerRegisterFilters: #204. I also included the Java part from PR #194 because it is the same feature. 

I will comment the "XHTML Source" log directly in develop, and we will have to monitor any issue with not including the MIMEtypes changes for ACS6 files. Closing the PR.

**Comment by danielweck** [comment]
@mmenu-mantano yes, let's just comment `NSLog(@"XHTML SOURCE: %@", dataStr);` but not remove it entirely. Thanks! :)

**Comment by bluefirepatrick** [comment]
@mmenu-mantano regarding the remaining features that you fear may be relegated to limbo -let us know what we can do to help.  @nleme will be taking a look at #204 with respect to the ContentFilter chain but we would be happy to look at any other parts of the PR that you feel need to be added to the SDK.

**Comment by mmenu-mantano** [comment]
@bluefirepatrick Thank you. :) For this PR I think everything important will be merged eventually (see #201 and #204).

Before that I didn't want to overload the PR list with multiple small PRs, but now I can see that a big one is an obstacle for integration and review.

I will make sure from my side to always make pull requests that are small, focused and tight from now on. It would be great if you can then review and merge them (PRs in general, not mine) more swiftly if no objection comes out of triage meetings.

If we don't merge the PRs into develop ASAP, they diverge too much, and we can't test them either as implementers. I don't think develop should be considered a "stable" branch, master is here for that.

**Pull request closed without merging**
