### PR TITLE
added android x86 support to NDK toolchain

### PR DESCRIPTION
**Pull request by ph0b**
Hi,

I have added support for android x86 target.
Basically added the x86 prebuilts for 3rd party libraries that are used and fixed code and toolchain so it correctly compiles an additional libepub3.so library inside the generated libs/x86 folder.
I've compiled it with NDK r10b and tested it with 'SDKLauncher-Android' and  'Readium_SDK_Test_Android' on a x86 Android device without encountering any issue.

### CODE REVIEW

**Comment by danielweck** [comment]
Thanks, I am going to give this a try!

**Comment by danielweck** [comment]
Damn, my OSX Core2 Duo 64 bits CPU is not supported by HAXM emulation, so I can't test this x86 (32 bits) build of ReadiumSDK / SDKLauncher-Android ! (my Android hardware is currently broken)

Never mind, I'll switch to my Windows Core i7 machine.

**Comment by danielweck** [comment]
@ph0b (Xavier) Thanks again for your Pull Request. Could you please briefly explain how you generated the new x86 libs? We don't want people to ship Readium-based applications that contain pre-built libs from unknown provenance, and as Readium is open-source it makes sense to be transparent about these kinds of external contributions.

Side topic: I recently re-read your blog post about Android Studio, Gradle, and NDK (good stuff):
http://ph0b.com/android-studio-gradle-and-ndk-integration/
@JCCR (Juan) and other devs discussed how we could streamline Readium's existing 2-project Eclipse setup into a more elegant and practical build process (possible Gradle-based, in order to migrate to Android Studio). We currently rely on multi-platform shell scripts such as `MakeHeaders.sh` and `ndk-compile.sh` to build the ReadiumSDK lib, which are somehow integrated into Eclipse as project Builders...but it's probably unnecessarily complicated. We'll continue evaluating our choices, but in the meantime your input is welcome.

**Comment by danielweck** [comment]
@ph0b for your information, I created a new feature branch in the Readium repository, based on the current develop branch, and containing your pre-built libs. Obviously, I used your makefile tweaks as well, and you will be fully credited as the contributor (I just modified minor things compared to this Pull Request).

https://github.com/readium/readium-sdk/tree/feature/android-NDK-x86

https://github.com/readium/SDKLauncher-Android/tree/feature/android-NDK-x86

**Comment by ph0b** [comment]
@danielweck Thanks! regarding the prebuilts, I've used https://github.com/MysticTreeGames/Boost-for-Android ; https://github.com/android-native-libraries/openssl-android and for ICU I've followed the ICU part of this tutorial: http://wudev.digitaltorque.com/2014/03/building-readium-for-x86-android.html

Your ndk-compile.sh step could be eliminated so a call to ndk-build would work directly, but in any case in order to migrate over Android Studio you can keep everything as is and have your scripts called from a Task in build.gradle, like in this gist: https://gist.github.com/ph0b/9e59058ac59cac104398

**Comment by danielweck** [comment]
Awesome, thanks Xavier!

By the way, the HAXM emulator still fails to load on my OSX machine (Intel Core2 Duo), even with an x86 image of vanilla Android. However, I successfully managed to test x86 SDKLauncher-Android on Windows (Core i7), via a x86-64 image of Lollipop API-21. It's still somewhat slow though, not sure why yet. Still, that's progress :)

**Comment by danielweck** [comment]
FYI, I added READMEs to the library folders:
https://github.com/readium/readium-sdk/commit/490daf3a597caede940fb26ee923caa0444764bc
(so that the original source code can be identified, along with documentation references on how to build from scratch)

**Comment by jmgeffroy** [comment]
Hello Daniel and @ph0b (Xavier),
While trying to prepare a patch for Readium, we noticed that we're using this code from Xavier since a while in our own app, and it works pretty well. So to keep our patch clean we'll temporarily drop the code related to x86 compat, but it would be great to see this PR integrated, isn't it ?
Jean-Marie

**Comment by danielweck** [comment]
@jmgeffroy I have been using this feature branch too, LGTM!

**Comment by danielweck** [comment]
I am setting up an up-to-date merge-able PR, to the develop branch (not master).

**Comment by danielweck** [comment]
Done:
https://github.com/readium/readium-sdk/pull/197

**Pull request closed without merging**
